---
output: 
  html_document:
    includes:
      in_header: cssloaders_in_header.html
self_contained: yes
runtime: shiny
css: styles.css
---

# 116th Congressional members within ANEP boundaries {.tabset .tabset-pills}
  
Source code [here](https://github.com/tbep-tech/anep-congressional) 

```{r setup, message = F, warning = F, results = 'hide', echo = FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F, fig.path = 'figs/', dev.args = list(family = 'serif'), fig.path = 'figures/')

library(tidyverse)
library(reactable)
library(here)
library(mapview)
library(shiny)
library(shinyWidgets)
library(shinycssloaders)
library(leaflet)

# # style file
# styles <- readLines('https://raw.githubusercontent.com/tbep-tech/css-styling/master/styles.css')
# writeLines(styles, 'styles.css')

data(anep)
data(cgrs)
data(hsedat)

mptyps <- c("CartoDB.Positron", "CartoDB.DarkMatter", "OpenStreetMap", "Esri.WorldImagery", "OpenTopoMap")

downloadButtonRmd <- function (outputId, label = "Download", class = NULL, ...)  {
  tags$a(id = outputId, class = paste("btn btn-default shiny-download-link", 
                                      class), href = "", target = "_blank", download = NA, 
         icon("download"), label, ...)
}

nepopt <- hsedat %>% 
  pull(nep) %>% 
  unique %>% 
  sort
```

```{r reactives}
seldat <- reactive({
  
  # inputs
  nepsel <- input$nepsel
  
  out <- hsedat %>% 
    filter(nep %in% nepsel) %>% 
    mutate(
      per_in_shed = round(per_in_shed, 1)
    ) %>% 
    select(
      NEP = nep,
      Name = name,
      District = district,
      State = state, 
      Office = office, 
      Party = party, 
      `% of district in NEP shed` = per_in_shed
    ) %>% 
    arrange(NEP, Name)
  
  return(out)
  
})

# reactable table from seldat
seltab <- reactive({
  
  # input
  seldat <- seldat()
  
  out <- reactable(
      seldat,
      groupBy = 'NEP',
      columns = list(
          NEP = colDef(name = '', minWidth = 200)
        ),
      defaultColDef = colDef(
        footerStyle = list(fontWeight = "bold"),
        format = colFormat(digits = 0, separators = TRUE),
        resizable = TRUE
      )
    )
  
})

# map selection
selmap <- reactive({
  
  nepsel <- input$nepsel
  seldat <- seldat()
  
  req(nepsel)
  
  # merge seldat state and districts
  seldatmrg <- seldat %>% 
    unite('lab', state, district, sep = ' ')
  
  # anep boundaries
  `NEP boundaries` <- anep %>% 
    filter(nep %in% nepsel)

  # cgrs boundaries
  `Congressional boundaries` <- cgrs %>% 
    unite('lab', state, district, sep = ' ') %>% 
    filter(lab %in% seldatmrg$lab)
 
  out1 <- mapview(`NEP boundaries`, label = `NEP boundaries`$nep, legend = F, map.types = mptyps)
  out2 <- mapview(`Congressional boundaries`, col.regions = 'tomato1', label = `Congressional boundaries`$lab, legend = F, map.types = mptyps)
  
  out <- out2 + out1
  out <- out@map
  
  return(out)
  
})
```

```{r downloads}
output$dltab <- downloadHandler(
  filename = function() {'house_data.csv'},
  content = function(file) {
    todl <- seldat()
    write.csv(todl, file, quote = T, row.names = F)
  }
)
```

```{r}
column(12, 
       column(6,
              pickerInput(inputId = "nepsel", label = 'Select NEPs:', choices = nepopt,
        options = list(`actions-box` = TRUE, size = 20), selected = nepopt, multiple = TRUE)     
              ), 
       column(6, 
              downloadButtonRmd('dltab', 'Download selected data')
              )
)
```

## Table

```{r}
output$seltab <- renderReactable(seltab()) 
reactableOutput('seltab') %>% withSpinner()
```

## ANEP boundaries

```{r}
output$selmap <- renderLeaflet(selmap())
column(12, 
  leafletOutput('selmap', height = 700) %>% withSpinner()
)
```
